# Generated by Django 4.0.2 on 2022-04-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='pid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
